<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automobile</name>
   <tag></tag>
   <elementGuidId>d307bbae-3745-4858-a44c-f259a71813ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_automobile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav_automobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Automobile&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e945698b-c76a-411b-a5da-3dbe7b066530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_automobile</value>
      <webElementGuid>0e51c24a-411b-4496-8f92-28453258aaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Navigation Automobile</value>
      <webElementGuid>c2d43ad2-bbdf-4b31-8e9b-1055e169a9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b9af960f-b1ca-4b55-a46a-8cdf4ac61890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoapp('Automobile');</value>
      <webElementGuid>698fdba0-d093-415b-a700-4d79f672981b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automobile</value>
      <webElementGuid>454754f7-5d03-4bdb-828f-e2dbf3920495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/header[@class=&quot;site-header&quot;]/div[@class=&quot;bottom-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-navigation&quot;]/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/a[@id=&quot;nav_automobile&quot;]</value>
      <webElementGuid>44bc4540-cefa-4d41-828c-8ebd5be7e803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_automobile']</value>
      <webElementGuid>67cff237-dd65-4847-9085-24e27458b57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/header/div[2]/div/div/ul/li/a</value>
      <webElementGuid>de213f6a-c1dd-419e-a939-badf79ea2c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Automobile')]</value>
      <webElementGuid>ce624c90-86d9-4c22-9ee5-2472115917dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Support!'])[1]/following::a[1]</value>
      <webElementGuid>7b48f127-a0e7-48eb-99ed-df48f37ff680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a sample application, Version 1.0.1'])[1]/following::a[2]</value>
      <webElementGuid>43a50ce9-b4e0-4b9a-9d87-e8eba8323a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Demo'])[1]/preceding::a[4]</value>
      <webElementGuid>c59a52da-50d2-4372-be89-31e327aa57a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automobile']/parent::*</value>
      <webElementGuid>a2ebc045-da94-4ccd-b4d2-1a3173e930ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>85873d63-48f8-4c7f-9fba-eb5693f1f474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>3c4f1d86-9f74-4512-af3a-65fd43769705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_automobile' and @name = 'Navigation Automobile' and @href = '#' and (text() = 'Automobile' or . = 'Automobile')]</value>
      <webElementGuid>a9f18756-d6b9-4b11-85a0-8e484b198529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
