<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>cc5d2aa2-00b4-41a4-b3ce-cb0fd52cac78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nextenterinsurantdata']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nextenterinsurantdata</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next »&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>200fa52d-8fb2-408c-87c2-25c01478d112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextenterinsurantdata</value>
      <webElementGuid>a5ea0d9c-0993-4179-a126-b0ee58a12501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Next (Enter Insurant Data)</value>
      <webElementGuid>7b28f0d3-20c1-4a50-a2ac-ac996c1d2197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f5cd2e8-3bd0-4121-a19d-a5e1a737e3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next button</value>
      <webElementGuid>f22ec67b-8dbe-467e-a83f-01873d3cc270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next »</value>
      <webElementGuid>c0ad2d96-44ec-452b-8831-e94846a04993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextenterinsurantdata&quot;)</value>
      <webElementGuid>3b58fe42-c0ed-49b4-905e-a2e57a42abba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nextenterinsurantdata']</value>
      <webElementGuid>97d28559-472d-4087-a47d-29308344ab0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[9]/button</value>
      <webElementGuid>d3c8d3bc-ad81-48af-8f63-521e81582855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be a number between 100 and 100000'])[1]/following::button[1]</value>
      <webElementGuid>74d15a2a-d372-42b7-8c8b-4aa15ccd51ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual Mileage [mi]'])[1]/following::button[1]</value>
      <webElementGuid>5f93e5bd-eb6d-4dc4-b8a7-a4757704f8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::button[1]</value>
      <webElementGuid>e8883a45-c124-45d2-9e73-db0ae8aed403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is mandatory'])[1]/preceding::button[1]</value>
      <webElementGuid>75edd062-cb63-458c-bf03-3a4176a5d6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next »']/parent::*</value>
      <webElementGuid>21efba04-9e10-4e80-877a-17e4ae5d6173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>37928fcb-7c98-4804-8723-acd0e8034ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nextenterinsurantdata' and @name = 'Next (Enter Insurant Data)' and @type = 'button' and (text() = 'Next »' or . = 'Next »')]</value>
      <webElementGuid>6619f9cf-4ffc-4608-a11e-d48131238ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
