<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_please select                       _4f72fa</name>
   <tag></tag>
   <elementGuidId>417b6bd5-609c-4858-b11d-932c6ad46d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='make']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#make</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#make</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>64e8a89b-cd2f-4840-bfeb-e25e8499b7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>make</value>
      <webElementGuid>7db0458d-2939-487f-85e1-6cbbde6237a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Make</value>
      <webElementGuid>0ac762e4-48be-486a-a694-5053484ac1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            – please select –
                                            Audi
                                            BMW
                                            Ford
                                            Honda
                                            Mazda
                                            Mercedes Benz
                                            Nissan
                                            Opel
                                            Porsche
                                            Renault
                                            Skoda
                                            Suzuki
                                            Toyota
                                            Volkswagen
                                            Volvo
                                        </value>
      <webElementGuid>41bfd9c0-bf5e-49bf-a0df-82aebb3ac2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;make&quot;)</value>
      <webElementGuid>acc347f8-3f63-440a-8e54-eb3a694db559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='make']</value>
      <webElementGuid>eb8b37be-f6a2-49d6-8993-5aa3334dfd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div/select</value>
      <webElementGuid>4e499ab4-168d-49dd-9a57-1c3614921d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make'])[1]/following::select[1]</value>
      <webElementGuid>3fdb1faf-57e1-4ed7-a820-dd28483c2d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automobile Insurance'])[1]/following::select[1]</value>
      <webElementGuid>83b6fdb9-0b3a-4c15-838c-a0a5d337bf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option'])[1]/preceding::select[1]</value>
      <webElementGuid>8b701769-1f48-49f5-8827-104c02b2903b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engine Performance [kW]'])[1]/preceding::select[1]</value>
      <webElementGuid>52431ed1-03dc-4e14-8a70-c57ca9c23179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c2fde6b2-82a8-4cda-a418-50b25ef069c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'make' and @name = 'Make' and (text() = '
                                            – please select –
                                            Audi
                                            BMW
                                            Ford
                                            Honda
                                            Mazda
                                            Mercedes Benz
                                            Nissan
                                            Opel
                                            Porsche
                                            Renault
                                            Skoda
                                            Suzuki
                                            Toyota
                                            Volkswagen
                                            Volvo
                                        ' or . = '
                                            – please select –
                                            Audi
                                            BMW
                                            Ford
                                            Honda
                                            Mazda
                                            Mercedes Benz
                                            Nissan
                                            Opel
                                            Porsche
                                            Renault
                                            Skoda
                                            Suzuki
                                            Toyota
                                            Volkswagen
                                            Volvo
                                        ')]</value>
      <webElementGuid>c7cdae37-f086-4541-85d4-733ccb9d3ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
